CapsLock시 색 변경
lauvsong/language-cursor pull request #36
Opened 2024-02-03 18:15 UTC by myoun

로컬에서 테스트해보니 정상 작동 합니다.
하지만 몇가지 알려드릴게 있어 남깁니다.

1. 커서 색 변경을 LanguageCheckService#switchCursorColorByLanguage에서 수행하고 있었는데, CapsLock 색 변경을 추가하려면 기존 서비스에 코드를 추가해야되므로 LanguageCheckServer의 클래스 이름을 CheckService로 변경하였습니다.
2. 한글/CapsLock(영어)/CapsLock(한글) 세가지 경우를 생각해야 하는데, 따라서 각각 색을 다르게 만들었습니다. 이 과정에서 기존 cursorColor라는 변수의 이름을 nonEnglighCursorColor, 나머지 두개의 이름을 capsLockCursorColor, nonEnglishCapsLockCursorColor로 변경했습니다. 하지만, 이름이 너무 길다는 생각이 들수도 있을 것 같습니다.

제가 수정할 점이 있으면 남겨주세요. 수정하고 커밋하겠습니다.

2024-02-07 16:16 UTC, lauvsong requested changes

2024-02-07 16:16 UTC, lauvsong commented on src/main/kotlin/com/github/lauvsong/langcursor/services/CheckService.kt
> +object CheckService {
네이밍 변경 `CheckService` 도 좋지만,
아예 services 디렉토리를 벗어나서 `InputChecker` 같은 이름은 어떨까요?
`services`는 비즈니스 로직을 담고 있는 경우로 생각하고 둔거긴 한데
이 파일은 `scheduledExecutor` 로 스케줄러 역할도 하는지라, 저런 이름으로 가져가도 적절할 것 같아요

2024-02-07 16:16 UTC, lauvsong commented on src/main/kotlin/com/github/lauvsong/langcursor/settings/AppSettingsComponent.kt
> +            .addLabeledComponent(JBLabel("Non-English CapsLock cursor color"), nonEnglishCursorColor, 3, false)
개인적인 생각은
non-english와 CapsLock의 조합에 따라 다른 색을 만들어주는건
앞으로 다른 기능을 추가했을 때도 새로운 조합 색 설정을 만들어줘야 한다는거라, 기능 확장이 복잡할 수 있을 것 같습니다.

아래처럼 하는건 어떨까 싶은데, 수정 가능할까요 ?
영어 여부와 CapsLock의 조합은 고려하지 않고, 각각 별도의 색상을 가진다.
단, CapsLock의 색상이 우선순위가 가장 높다.

2024-02-07 16:18 UTC, lauvsong commented on src/main/kotlin/com/github/lauvsong/langcursor/core/CapsLockCheckStrategy.kt
> +    val capsLock = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)
이렇게 캡스락을 알아낼 수 있군요 bb
찾아주셔서 감사해요

2024-02-08 14:29 UTC, myoun commented on src/main/kotlin/com/github/lauvsong/langcursor/services/CheckService.kt
> +object CheckService {
그럼 InputChecker의 패키지는 어떻게 처리해야할까요?

2024-02-08 14:42 UTC, myoun commented on src/main/kotlin/com/github/lauvsong/langcursor/services/CheckService.kt
> +object CheckService {
일단은 최상위 패키지로 옮겼습니다.

2024-02-09 15:36 UTC, lauvsong commented on src/main/kotlin/com/github/lauvsong/langcursor/services/CheckService.kt
> +object CheckService {
거의 메인 기능을 다 담당하는 클래스라
최상위 패키지가 적절한 것 같습니다. bb

2024-02-09 17:29 UTC, lauvsong commented
LGTM!! 수정 반영해주셔서 감사해요
머지하고 1.1.0 버전 배포에 포함할게요!

2024-02-09 17:30 UTC, merged